### ISSUE TITLE
Push notifications with iOS 13 don't work

### ISSUE THREAD

**Issue by MarcoLude** [esl/MongoosePush#105]
Hi all,

We were testing our implementation of mongooseIM (version 3.4.0) with mongoosePush(1.0.5) with 2 iPhone, one with iOS 12 and one with iOS 13. We use a simple XMPP client.
On iOS 12 push notifications work ok, but on iOS 13 they don't work at all: we don't receive push notifications.
We are checking if it is a client issue, meanwhile, could you check if mongoosePush is iOS 13 compatible?

Thank you

**Comment by rslota** [comment]
Hi @MarcoLude ,

Do you happen to use silent push notifications or regular ones?
