### ISSUE TITLE
1.0.5 release docker image has faulty ssl-9.2

### ISSUE THREAD

**Issue by mikesilky** [esl/MongoosePush#117]
Hello,

We are using the current 1.0.5 release of MongoosePush and have been having intermittent problems with connecting out to remote services to send push notifications.

The 1.0.5 MongoosePush docker image has ssl-9.2.

Upon investigation we have see that the problem is being caused by https://bugs.erlang.org/browse/ERL-883 and https://bugs.erlang.org/browse/ERL-884.

These issues are fixed in OTP 21.3.1 and ssl-9.2.1.

It would be great if a new release could be made which contains this, I bet we are not the only people affected by this issue.

Cheers

 - Mike

**Comment by rslota** [comment]
Hi @mikesilky ,

I just drafted a new release - `1.0.6`, please give it a try. It's functionally the same, only updated to be compatible with our new release workflows that we use for current `2.x` releases. This essentially means that the docker image for `1.0.6` is built with Erlang/OTP 22.0 and Elixir 1.9, and thus the `ssl` app version should be `9.3.3`.

**Comment by rslota** [comment]
Closing this one. If the issue persists, please open a new issue.
