### ISSUE TITLE
KEY_ID TEAM_ID apns

### ISSUE THREAD

**Issue by andrewvmail** [esl/MongoosePush#119]
Not sure if it's something on my end or what, but seems like the environment variable is reversed? I get a InvalidProviderToken until i swapped the key and team. Inspecting the resulted JWT token you see kid gets filled out with the team id...

**Comment by rslota** [comment]
Hi @andrewvmail ,

Thanks for reporting the issue! Indeed the order is not correct. The issue will be fixed as soon as the following PRs will be closed:
- https://github.com/esl/sparrow/pull/27
- #120
