### ISSUE TITLE
Swagger

### ISSUE THREAD

**Issue by ppcharli** [esl/MongoosePush#138]
Swagger does not work

```
https:/host:8443/swagger.json
{"details":"This is not the endpoint you are looking for."}
```

Thanks,

**Comment by rslota** [comment]
@ppcharli ,

Swagger is not enabled in `prod` images. Unfortunately this is not configurable at this moment though this may change in near future. You can however rebuild the image yourself with swagger enabled - line responsible for that is: https://github.com/esl/MongoosePush/blob/618009e6f0ae10b9577c1bc375e273dd452428ac/lib/mongoose_push/router.ex#L13 .

**Comment by rslota** [comment]
@ppcharli ,

I hope my last post answers your questions. Please reopen the issue otherwise.
