### ISSUE TITLE
where do I find sys.config?

### ISSUE THREAD

**Issue by chrisatta** [esl/MongoosePush#197]
when i run 
docker run -h mongoosepush -p 8443:8443 -v `pwd`/priv:/opt/app/priv -e PUSH_HTTPS_CERTFILE="/opt/app/priv/ssl/rest_cert.pem"  -e PUSH_HTTPS_KEYFILE="/opt/app/priv/ssl/rest_key.pem"  -e PUSH_APNS_ENABLED=0 -it --rm mongooseim/mongoose-push:latest

and run
 docker cp mongoosepush:/opt/app/var/sys.config sys.config

i have this error
Error: No such container:path: mongoosepush:/opt/app/var/sys.config

**Comment by pawlooss1** [comment]
There are two issues here:
- in `docker cp` command you refer to the container as `mongoosepush` but you haven't give it such name when starting it (hence the docker runtime should give it some random name) - please add an option `--name mongoosepush` to your `docker run` command
- `sys.config` file is located at `/opt/app/releases/<release version>/sys.config`
