### ISSUE TITLE
Is it possible to disable SSL certificate for http endpoint?

### ISSUE THREAD

**Issue by RomanOlegovich** [esl/MongoosePush#199]
Can I remove certificate options from prod.exs to disable httpS.

**Comment by aleklisi** [comment]
Hello,
If I understand correctly, you can do it in the same fashion as you would in any phoenix project. Just remove the [https section](https://github.com/esl/MongoosePush/blob/6c8c53234f8623a1abeb115c8fbdab691a95ed2f/config/prod.exs#L8-L29) from the `config/prod.exs` config.  See this article on [enabling](https://hexdocs.pm/phoenix/using_ssl.html) and [endorsing](https://elixirforum.com/t/proper-way-to-enforce-https-only/2117/2) SSL, and just not do what they say.

**Comment by pawlooss1** [comment]
Closing the issue due to lack of activity.
