### ISSUE TITLE
Is it possible to send apns notification to fcm while using with mongooseim

### ISSUE THREAD

**Issue by alvinlal** [esl/MongoosePush#209]
i have setup cloud messaging in firebase to work with apns , so i have setup only fcm configuration and set `PUSH_APNS_ENABLED=0` in docker env, is it possible to define service as apns in enable stanza of XEP-0357 and let mongoosepush deliver apns notification to fcm ? , or do i always have to configure both fcm and apns to send notification to android and ios devices.

**Comment by pawlooss1** [comment]
Hello @alvinlal. Unfortunately MongoosePush currently does not support such feature. Based on my quick research sparrow library allows it, so integration is possible. Are you still interested in such feature? I could create an internal backlog entry and we could discuss with the team if this should be on our roadmap.

**Comment by alvinlal** [comment]
@pawlooss1 , it would be a great feature to have since its easier to manage everything in fcm instead of setting up fcm and apns seperatly, for now i have setup fcm and apns seperately 👍
