### ISSUE TITLE
Possible to run without TLS/HTTPS? (Cluster Internal)

### ISSUE THREAD

**Issue by hartmut-pq** [esl/MongoosePush#27]
Hi, 

if I would want to access cluster internal on http only - is this doable, how? 
Or may I need to build my own image with a modified config? 

Thanks
Hartmut

**Comment by rslota** [comment]
Hi @hartmut-pq ,

I didn't test this, but in theory you could edit the sys.config on existing image or `config/prod.exs` before building to achieve this quite easily. Look at the `config :maru, MongoosePush.Router` configuration - there is `https` "key". If you change it to `http` and remove all TLS related subkeys (i.e. `certfile` and `keyfile`) it's possible that it will "just work". But as I said, I've never tried this before.

**Comment by hartmut-pq** [comment]
thx, will have a look

I've jumped ahead otherwise and tried to build myself with a modified config file.

README build section doesn't seem up to date? 
tried `ENV=pq MIX_ENV=pq docker build -f ./Dockerfile.build .`

but failed with
`** (Mix) Could not compile dependency :chatterbox, "/opt/app/.mix/rebar3 bare compile --paths "/opt/app/_build/prod/lib/*/ebin"" command failed. You can recompile this d
ependency with "mix deps.compile chatterbox", update it with "mix deps.update chatterbox" or clean it with "mix deps.clean chatterbox"`

> **full build log**
> https://pastebin.com/Bvazr20i

Further - with a up and running default image & TLS - I tried the described `/swagger.json` route without success:
`curl -k https://mongoosepush:8443/swagger.json`
=> `{"details":"This is not the endpoint you are looking for."}`

**Comment by hartmut-pq** [comment]
`cat /opt/app/var/WARNING_README`
says 
> Files in this directory are regenerated frequently, edits will be lost

so I don't think you can mount/hack the image without building a separate version...
any help on how to fix the build issues would be appreciated!

**Comment by rslota** [comment]
I'm sorry, apparently there is an issue with the OTP version that is downloaded in docker builder - it downloads Erlang 20 which is still incompatible with some dependencies as well as with Elixir 1.4.x itself. 
I have made a fix in #28, so you either need to wait for it to be merged or just switch to branch `static_erl_version`.

**Comment by rslota** [comment]
Btw. I have verified that the config change I described earlier do indeed work and enables HTTP access.

**Comment by rslota** [comment]
> so I don't think you can mount/hack the image without building a separate version...
any help on how to fix the build issues would be appreciated!

You can copy the `/opt/app/var/sys.config` to `/opt/app/sys.config` and edit the copy. The `/opt/app/sys.config` will override the `/opt/app/var/sys.config`.

**Comment by hartmut-pq** [comment]
@rslota thanks a lot! Got it up and running now!

One more question - what's the swagger ui route? `/swagger.json` doesn't seem to work.
Further - Is there any route / endpoint I can use for (liveness) health checks? It needs to return http 2xx.

**Comment by rslota** [comment]
> One more question - what's the swagger ui route? /swagger.json doesn't seem to work.
Further - Is there any route / endpoint I can use for (liveness) health checks? It needs to return http 2xx.

Swagger is disabled on production environment. In future I may make it configurable, but for now you would need to remove [this line](https://github.com/esl/MongoosePush/blob/master/lib/mongoose_push/router.ex#L13) (or set it to empty list) to enable this endpoint. 
For now the is no health check available but assuming you will enable Swagger API, you could for now use `/swagger.json`.

**Comment by rslota** [comment]
@hartmut-pq ,

Is there anything else regarding HTTP endpoint, or can we close the issue?

**Comment by hartmut-pq** [comment]
Hi @rslota - never tested enabling swagger for didn't need to - can't see why you're suggestion wouldn't work though. All working otherwise, thx again!
