### ISSUE TITLE
Docker fail to find key file. although it is there.

### ISSUE THREAD

**Issue by Mo33n** [esl/MongoosePush#30]
[root@ivr ssl]# ls -l /opt/app/priv/ssl/
total 12
-rw-r--r--. 1 root root 6641 Jun 23 12:07 server.crt
-rw-r--r--. 1 root root 1679 Jun 23 12:07 server.key

[root@ivr ssl]# docker run -v /usr/lib/mongooseim/priv/ssl:/opt/app/priv   -e PUSH_FCM_APP_KEY="AAAA5y_R5rA:APA91bGUmR7xsghMfgpudP64lt1JdJ2XBqxYLijGerdIaLI7Z4ZXqYfVRYjqKIUm6opCvEvS5H8m_KEtr9J_VRJlX9Ge7U-U5S2dasjjx0LtxQfjCSddhwxYXgR4goX8fBStIdoYikYM"   -e PUSH_HTTPS_CERTFILE="/opt/app/priv/ssl/server.crt" -e PUSH_HTTPS_KEYFILE="/opt/app/priv/ssl/server.key" -it --rm mongooseim/mongoose-push:latest

12:12:09.270 [info]  Setup running ...

12:12:09.273 [info]  Directories verified. Res = :ok

12:12:09.273 [info]  Setup finished processing hooks (Mode=:normal)...

12:12:09.279 [info]  Starting Elixir.MongoosePush.Router with Cowboy on https://0.0.0.0:8443

12:12:09.281 [info]  Application maru exited: exited in: Maru.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (ArgumentError) could not start Cowboy adapter, the file /opt/app/priv/ssl/server.key required by SSL's :keyfile either does not exist, or the application does not have permission to access it
            (plug) lib/plug/adapters/cowboy.ex:245: Plug.Adapters.Cowboy.fail/1
            (plug) lib/plug/adapters/cowboy.ex:222: Plug.Adapters.Cowboy.put_ssl_file/3
            (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
            (plug) lib/plug/adapters/cowboy.ex:167: Plug.Adapters.Cowboy.normalize_cowboy_options/2
            (plug) lib/plug/adapters/cowboy.ex:49: Plug.Adapters.Cowboy.args/4
            (plug) lib/plug/adapters/cowboy.ex:137: Plug.Adapters.Cowboy.child_spec/4
            (maru) lib/maru.ex:32: anonymous fn/4 in Maru.start/2
            (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
12:12:09.240 [error] Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.1109.0> exit with reason normal in context child_terminated
12:12:09.267 [info] Application lager started on node 'mongoose_push@127.0.0.1'
12:12:09.267 [info] Application asn1 started on node 'mongoose_push@127.0.0.1'
12:12:09.267 [info] Application crypto started on node 'mongoose_push@127.0.0.1'
12:12:09.267 [info] Application public_key started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Application ssl started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Application chatterbox started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Application metrics started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Application ssl_verify_fun started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Application certifi started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Application mimerl started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Application idna started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Application hackney started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Application httpoison started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Application pigeon started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Application pobox started on node 'mongoose_push@127.0.0.1'
12:12:09.270 [info] Setup running ...
12:12:09.273 [info] Directories verified. Res = ok
12:12:09.274 [info] Setup finished processing hooks (Mode=normal)...
12:12:09.274 [info] Application setup started on node 'mongoose_push@127.0.0.1'
12:12:09.276 [info] Starting reporters with []
12:12:09.278 [info] Application exometer_core started on node 'mongoose_push@127.0.0.1'
12:12:09.278 [info] Application elixometer started on node 'mongoose_push@127.0.0.1'
12:12:09.278 [info] Application exometer started on node 'mongoose_push@127.0.0.1'
12:12:09.278 [info] Application cowlib started on node 'mongoose_push@127.0.0.1'
12:12:09.278 [info] Application ranch started on node 'mongoose_push@127.0.0.1'
{"Kernel pid terminated",application_controller,"{application_start_failure,maru,{bad_return,{{'Elixir.Maru',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError',message => <<\"could not start Cowboy adapter, the file /opt/app/priv/ssl/server.key required by SSL's :keyfile either does not exist, or the application does not have permission to access it\">>},[{'Elixir.Plug.Adapters.Cowboy',fail,1,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,245}]},{'Elixir.Plug.Adapters.Cowboy',put_ssl_file,3,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,222}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,\"lib/enum.ex\"},{line,1755}]},{'Elixir.Plug.Adapters.Cowboy',normalize_cowboy_options,2,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,167}]},{'Elixir.Plug.Adapters.Cowboy',args,4,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,49}]},{'Elixir.Plug.Adapters.Cowboy',child_spec,4,[{file,\"lib/plug/adapters/cowboy.ex\"},{line,137}]},{'Elixir.Maru','-start/2-fun-0-',4,[{file,\"lib/maru.ex\"},{line,32}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,\"lib/enum.ex\"},{line,1755}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,maru,{bad_return,{{'Elixir.Maru',start,[normal,[]]},{'EXIT',{#{'__exception__' => true,'__struct__' => 'Elixir.ArgumentError'

Crash dump is being written to: erl_crash.dump...done

Shutting down..
Node is not running!

**Comment by rslota** [comment]
Hi @Mo33n ,

Please note that you are mounting `/usr/lib/mongooseim/priv/ssl` to `/opt/app/priv`, which means that there is no `/opt/app/priv/ssl` directory that you mentioned in configuration. 
Please try `-v /usr/lib/mongooseim/priv:/opt/app/priv`.

**Comment by Mo33n** [comment]
Hi @rslota , 

I have tried the following command, but issue is still the same.

I have placed my HTTPS certificate files in /opt/app/priv/ssl/

docker run -v /usr/lib/mongooseim/priv:/opt/app/priv   -e PUSH_FCM_APP_KEY="AAAA5y_R5rA:APA91bGUmR7xsghMfgpudP64lt1JdJ2XBqxYLijGerdIaLI7Z4ZXqYfVRYjqKIUm6opCvEvS5H8m_KEtr9J_VRJlX9Ge7U-U5S2dasjjx0LtxQfjCSddhwxYXgR4goX8fBStIdoYikYM"   -e PUSH_HTTPS_CERTFILE="/opt/app/priv/ssl/server.crt" -e PUSH_HTTPS_KEYFILE="/opt/app/priv/ssl/server.key" -it --rm mongooseim/mongoose-push:latest

**Comment by rslota** [comment]
You should place them in `/usr/lib/mongooseim/priv/ssl` on you host machine prior to running the command. Is that what you've done?

**Comment by Mo33n** [comment]
Thanks alot it worked now.
