### ISSUE TITLE
compilation error : Could not compile dependency :chatterbox

### ISSUE THREAD

**Issue by Mo33n** [esl/MongoosePush#34]
===> Compiling exometer
==> elixometer
Compiling 4 files (.ex)
Generated elixometer app
===> Compiling chatterbox
===> Compiling src/h2_stream.erl failed
src/h2_stream.erl:105: gen_fsm:start_link/3 is deprecated and will be removed in a future release; use gen_statem:start/3
src/h2_stream.erl:115: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1
src/h2_stream.erl:120: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1
src/h2_stream.erl:124: gen_fsm:sync_send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:call/2
src/h2_stream.erl:128: gen_fsm:sync_send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:call/2
src/h2_stream.erl:132: gen_fsm:send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1
src/h2_stream.erl:136: gen_fsm:send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1
src/h2_stream.erl:139: gen_fsm:sync_send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:call/2
src/h2_stream.erl:143: gen_fsm:stop/1 is deprecated and will be removed in a future release; use gen_statem:stop/1
src/h2_stream.erl:486: gen_fsm:send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1

==> mongoose_push
** (Mix) Could not compile dependency :chatterbox, "/root/.mix/rebar3 bare compile --paths "/home/mongoosePush/MongoosePush/_build/prod/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile chatterbox", update it with "mix deps.update chatterbox" or clean it with "mix deps.clean chatterbox"

**Comment by rslota** [comment]
Hi @Mo33n ,

It seems that you are using Erlang 20.0. Most of the dependencies of this project are still incompatible with this new release. Please try to use 19.3 for now.

**Comment by Mo33n** [comment]
okay let me try that.

**Comment by Mo33n** [comment]
degraded the elixer version to 19.3.

now getting this following error


Generated plug app
==> maru
Compiling 59 files (.ex)

== Compilation error in file lib/maru/plugs/version.ex ==
** (CompileError) lib/maru/plugs/version.ex:32: expected -> clauses for :else in "with"

could not compile dependency :maru, "mix compile" failed. You can recompile this dependency with "mix deps.compile maru", update it with "mix deps.update maru" or clean it with "mix deps.clean maru"

**Comment by Mo33n** [comment]
oky got the fix (e457bdc), Thanks.

**Comment by Mo33n** [comment]
Everything works fine, Thanks 
 (e457bdc)
