### ISSUE TITLE
Local Build Failing, Looks like issue with chatterbox

### ISSUE THREAD

**Issue by sourabhmodi20051** [esl/MongoosePush#35]
Got the following error while building

===> Compiling chatterbox
===> Compiling src/h2_stream.erl failed
src/h2_stream.erl:105: gen_fsm:start_link/3 is deprecated and will be removed in a future release; use gen_statem:start/3
src/h2_stream.erl:115: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1
src/h2_stream.erl:120: gen_fsm:send_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1
src/h2_stream.erl:124: gen_fsm:sync_send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:call/2
src/h2_stream.erl:128: gen_fsm:sync_send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:call/2
src/h2_stream.erl:132: gen_fsm:send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1
src/h2_stream.erl:136: gen_fsm:send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1
src/h2_stream.erl:139: gen_fsm:sync_send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:call/2
src/h2_stream.erl:143: gen_fsm:stop/1 is deprecated and will be removed in a future release; use gen_statem:stop/1
src/h2_stream.erl:486: gen_fsm:send_all_state_event/2 is deprecated and will be removed in a future release; use gen_statem:cast/1

==> mongoose_push
** (Mix) Could not compile dependency :chatterbox, "/home/ubuntu/.mix/rebar3 bare compile --paths "/home/ubuntu/MongoosePush-0.9.0/_build/prod/lib/*/ebin"" command failed. You can recompile this dependency with "mix deps.compile chatterbox", update it with "mix deps.update chatterbox" or clean it with "mix deps.clean chatterbox"

**Tried to blindly replace the functions, got error while running.**

**Comment by sourabhmodi20051** [comment]
Tried with erlang 19.3 and it worked

**Comment by rslota** [comment]
Hi @sourabhmodi20051 ,

I'm sorry, but Erlang/OTP 20.x is not yet supported. I tried to introduce support for that, but some dependencies don't really work and/or don't work correctly on the newest version of Erlang. 

I will eventually add support for Erlang/OTP 20.x, but for now it's not as easy as I would like it to be.
