### ISSUE TITLE
Docker fail to start with the error of maru

### ISSUE THREAD

**Issue by Mo33n** [esl/MongoosePush#38]
[root@ivr bin]# docker run -v /usr/lib/mongooseim/priv:/opt/app/priv -e PUSH_FCM_APP_KEY="AAAAC3sFy48:APA91bEHZGVesP4TycnyY5345ertegg34grY4RISfOL8S7CvPcQCL4Wv-dkLuopIzF7Xmn9_A1kp7WYVJW1PDH35Ju0LD_EdzHzcwvV1bhOuOEAGCB22bJ-WEmBndr154HwfoPGIYmoV"  -e PUSH_HTTPS_CERTFILE="/opt/app/priv/ssl/server.crt" -e PUSH_HTTPS_KEYFILE="/opt/app/priv/ssl/server.key" -e PUSH_HTTPS_BIND_ADDR="stage_chat.ninja.com" -e PUSH_HTTPS_PORT="443"  -e PUSH_LOGLEVEL="debug" -e PUSH_FCM_ENABLED="true" -e PUSH_APNS_ENABLED="false" -it --rm mongooseim/mongoose-push:latest

10:31:31.491 [info]  Setup running ...

10:31:31.493 [info]  Directories verified. Res = :ok

10:31:31.494 [info]  Setup finished processing hooks (Mode=:normal)...

10:31:31.502 [info]  Application maru exited: exited in: Maru.start(:normal, [])
    ** (EXIT) an exception was raised:
        ** (MatchError) no match of right hand side value: {:error, :einval}
            (maru) lib/maru.ex:76: Maru.to_ip/1
            (maru) lib/maru.ex:58: Maru.endpoint_spec/3
            (maru) lib/maru.ex:32: anonymous fn/4 in Maru.start/2
            (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
            (maru) lib/maru.ex:30: anonymous fn/2 in Maru.start/2
            (elixir) lib/enum.ex:1755: Enum."-reduce/3-lists^foldl/2-0-"/3
            (maru) lib/maru.ex:29: Maru.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4
10:31:31.465 [error] Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.1109.0> exit with reason normal in context child_terminated
10:31:31.487 [info] Application lager started on node 'mongoose_push@127.0.0.1'
10:31:31.488 [info] Application asn1 started on node 'mongoose_push@127.0.0.1'
10:31:31.488 [info] Application crypto started on node 'mongoose_push@127.0.0.1'
10:31:31.488 [info] Application public_key started on node 'mongoose_push@127.0.0.1'
10:31:31.489 [info] Application ssl started on node 'mongoose_push@127.0.0.1'
10:31:31.489 [info] Application chatterbox started on node 'mongoose_push@127.0.0.1'
10:31:31.489 [info] Application metrics started on node 'mongoose_push@127.0.0.1'
10:31:31.489 [info] Application ssl_verify_fun started on node 'mongoose_push@127.0.0.1'
10:31:31.489 [info] Application certifi started on node 'mongoose_push@127.0.0.1'
10:31:31.489 [info] Application mimerl started on node 'mongoose_push@127.0.0.1'
10:31:31.489 [info] Application idna started on node 'mongoose_push@127.0.0.1'
10:31:31.490 [info] Application hackney started on node 'mongoose_push@127.0.0.1'
10:31:31.490 [info] Application httpoison started on node 'mongoose_push@127.0.0.1'
10:31:31.490 [info] Application pigeon started on node 'mongoose_push@127.0.0.1'
10:31:31.491 [info] Application pobox started on node 'mongoose_push@127.0.0.1'
10:31:31.491 [info] Setup running ...
10:31:31.493 [info] Directories verified. Res = ok
10:31:31.494 [info] Setup finished processing hooks (Mode=normal)...
10:31:31.494 [info] Application setup started on node 'mongoose_push@127.0.0.1'
10:31:31.497 [info] Starting reporters with []
10:31:31.497 [info] Application exometer_core started on node 'mongoose_push@127.0.0.1'
10:31:31.498 [info] Application elixometer started on node 'mongoose_push@127.0.0.1'
10:31:31.498 [info] Application exometer started on node 'mongoose_push@127.0.0.1'
10:31:31.498 [info] Application cowlib started on node 'mongoose_push@127.0.0.1'
10:31:31.498 [info] Application ranch started on node 'mongoose_push@127.0.0.1'
{"Kernel pid terminated",application_controller,"{application_start_failure,maru,{bad_return,{{'Elixir.Maru',start,[normal,[]]},{'EXIT',{{badmatch,{error,einval}},[{'Elixir.Maru',to_ip,1,[{file,\"lib/maru.ex\"},{line,76}]},{'Elixir.Maru',endpoint_spec,3,[{file,\"lib/maru.ex\"},{line,58}]},{'Elixir.Maru','-start/2-fun-0-',4,[{file,\"lib/maru.ex\"},{line,32}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,\"lib/enum.ex\"},{line,1755}]},{'Elixir.Maru','-start/2-fun-1-',2,[{file,\"lib/maru.ex\"},{line,30}]},{'Elixir.Enum','-reduce/3-lists^foldl/2-0-',3,[{file,\"lib/enum.ex\"},{line,1755}]},{'Elixir.Maru',start,2,[{file,\"lib/maru.ex\"},{line,29}]},{application_master,start_it_old,4,[{file,\"application_master.erl\"},{line,273}]}]}}}}}"}
Kernel pid terminated (application_controller) ({application_start_failure,maru,{bad_return,{{'Elixir.Maru',start,[normal,[]]},{'EXIT',{{badmatch,{error,einval}},[{'Elixir.Maru',to_ip,1,[{file,"lib/ma

Crash dump is being written to: erl_crash.dump...done

Shutting down..
Node is not running!

**Comment by rslota** [comment]
Hi @Mo33n ,

The direct issue here is that option `PUSH_HTTPS_BIND_ADDR` requires IP address, while you have set a domain. But the story here is more complicated then that:

Options `PUSH_HTTPS_BIND_ADDR` and `PUSH_HTTPS_PORT` are not very useful in docker environment. Those options must specify the listen IP/Port, but in docker environment there is not much of a choice beside IP address "0.0.0.0" and whatever port docker listens to. You should really change that, since all clients have to connect to docker exposed port and docker IP address anyway, so the MongoosePush settings in this matter don't really matter here. 

My suggestion: just leave `PUSH_HTTPS_BIND_ADDR` and `PUSH_HTTPS_PORT` unset and run docker with flag `-p 443:8443` if you want you host machine to listen on port 443. That should just work.

**Comment by rslota** [comment]
@Hi @Mo33n ,

What is the status of this issue? Do you need some further help? If you don't, please let me know and/or close the issue. Thanks!

**Comment by Mo33n** [comment]
@rslota  i have checked out and complied the code it worked for me. 
thanks for the concern though.

**Comment by Mo33n** [comment]
Will try your suggestion , and i also believe that your suggestion should work, thanks for the help.
