### ISSUE TITLE
Fail while using with APNS.

### ISSUE THREAD

**Issue by Mo33n** [esl/MongoosePush#44]
12:22:49.774 [info]  Reconnecting to push service provider before request

12:22:49.869 [error] {:options, {:keyfile, '/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem', []}}

=CRASH REPORT==== 12-Oct-2017::12:22:49 ===
  crasher:
    initial call: h2_connection:init/1
    pid: <0.1432.0>
    registered_name: []
    exception exit: {options,{keyfile,"/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem",
                                      []}}
      in function  gen_fsm:init_it/6 (gen_fsm.erl, line 335)
    ancestors: [apns_prod_2,'Elixir.MongoosePush.Supervisor',<0.1393.0>]
    messages: []
    links: [<0.1406.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 1598
    stack_size: 27
    reductions: 5074
  neighbours:
12:22:49.870 [error] CRASH REPORT Process <0.1432.0> with 0 neighbours exited with reason: {options,{keyfile,"/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem",[]}} in gen_fsm:init_it/6 line 335

12:22:49.969 [error] {:options, {:keyfile, '/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem', []}}

=CRASH REPORT==== 12-Oct-2017::12:22:49 ===
  crasher:
    initial call: h2_connection:init/1
    pid: <0.1436.0>
    registered_name: []
    exception exit: {options,{keyfile,"/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem",
                                      []}}
      in function  gen_fsm:init_it/6 (gen_fsm.erl, line 335)
    ancestors: [apns_prod_2,'Elixir.MongoosePush.Supervisor',<0.1393.0>]
    messages: []
    links: [<0.1406.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 5030
  neighbours:

12:22:50.061 [error] {:options, {:keyfile, '/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem', []}}

12:22:50.061 [error] Failed to establish SSL connection. Is the certificate signed for :prod mode?

12:22:50.061 [info]  Reconnecting to push service provider before request

=CRASH REPORT==== 12-Oct-2017::12:22:50 ===
  crasher:
    initial call: h2_connection:init/1
    pid: <0.1438.0>
    registered_name: []
    exception exit: {options,{keyfile,"/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem",
                                      []}}
      in function  gen_fsm:init_it/6 (gen_fsm.erl, line 335)
    ancestors: [apns_prod_2,'Elixir.MongoosePush.Supervisor',<0.1393.0>]
    messages: []
    links: [<0.1406.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 5034
  neighbours:
12:22:49.969 [error] CRASH REPORT Process <0.1436.0> with 0 neighbours exited with reason: {options,{keyfile,"/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem",[]}} in gen_fsm:init_it/6 line 335

12:22:50.159 [error] {:options, {:keyfile, '/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem', []}}

=CRASH REPORT==== 12-Oct-2017::12:22:50 ===
  crasher:
    initial call: h2_connection:init/1
    pid: <0.1440.0>
    registered_name: []
    exception exit: {options,{keyfile,"/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem",
                                      []}}
      in function  gen_fsm:init_it/6 (gen_fsm.erl, line 335)
    ancestors: [apns_prod_2,'Elixir.MongoosePush.Supervisor',<0.1393.0>]
    messages: []
    links: [<0.1406.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 5038
  neighbours:
12:22:50.061 [error] CRASH REPORT Process <0.1438.0> with 0 neighbours exited with reason: {options,{keyfile,"/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem",[]}} in gen_fsm:init_it/6 line 335

12:22:50.250 [error] {:options, {:keyfile, '/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem', []}}

=CRASH REPORT==== 12-Oct-2017::12:22:50 ===
  crasher:
    initial call: h2_connection:init/1
    pid: <0.1442.0>
    registered_name: []
    exception exit: {options,{keyfile,"/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem",
                                      []}}
      in function  gen_fsm:init_it/6 (gen_fsm.erl, line 335)
    ancestors: [apns_prod_2,'Elixir.MongoosePush.Supervisor',<0.1393.0>]
    messages: []
    links: [<0.1406.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 5042
  neighbours:

12:22:50.308 [error] {:options, {:keyfile, '/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem', []}}

=CRASH REPORT==== 12-Oct-2017::12:22:50 ===
  crasher:
    initial call: h2_connection:init/1
    pid: <0.1444.0>
    registered_name: []
    exception exit: {options,{keyfile,"/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem",
                                      []}}
      in function  gen_fsm:init_it/6 (gen_fsm.erl, line 335)
    ancestors: [apns_prod_2,'Elixir.MongoosePush.Supervisor',<0.1393.0>]
    messages: []
    links: [<0.1406.0>]
    dictionary: []
    trap_exit: false
    status: running
    heap_size: 987
    stack_size: 27
    reductions: 5046
  neighbours:

12:22:50.308 [error] Failed to establish SSL connection. Is the certificate signed for :prod mode?

**Comment by rslota** [comment]
Hi @Mo33n ,

Are you sure `/home/MongoosePush/_build/prod/rel/mongoose_push/lib/mongoose_push-0.1.0/priv/apns/PushChatKey_Prod.pem` exists?

**Comment by Mo33n** [comment]
@rslota  Yes. I have manually checked the file.

**Comment by rslota** [comment]
This error propagates directly from Erlang's SSL client. This means that the keyfile is in some way invalid. It's either not accessible (doesn't exist or has wrong permissions), wrong format (not PEM encoded) or is encrypted (password protected). Can you please verify all those conditions?

**Comment by Mo33n** [comment]
I fixed it, There was some extra information inside the key file, Key file should only contain key. Not the information about the key .

Thanks @rslota
