### ISSUE TITLE
Unable to submit notification ErrorCode 400

### ISSUE THREAD

**Issue by Gdev82** [esl/MongoosePush#48]
I have setup MongooseIm (latest) with MongoosePush (docker image).

During regular one-to-one messaging the notifications work as expected. 

But when I create a room light, the hook for sending a notification is called (I assume) and a warning with the following message is printed out

`[warning] <0.910.0>@mod_push_service_mongoosepush:http_notification:109 Unable to submit push notification. ErrorCode 400, Payload <<"{\"details\":\"Parsing Param Error: body\"}">>   `

I am not sure how to debug this message. If you could point me to the right direction I would appreciate it. Thank you.

**Comment by rslota** [comment]
Hi @Gdev82 , 

This is more a MongooseIM issue. Currently the message filtering is done by function `mod_push:filter_packet` and there are several known issue with it. All those known issues should be resolved by this PR: https://github.com/esl/MongooseIM/pull/1414 . If you compile MIM from source, you could test it out.

**Comment by rslota** [comment]
Since the issue has been reported, there were quite a few changes on MongooseIM side that should resolve this issue. However, if it's not the case, please open new issue in [esl/MongooseIM](https://github.com/esl/MongooseIM) repository.
