### ISSUE TITLE
docker not working properly 

### ISSUE THREAD

**Issue by sanghinitin** [esl/MongoosePush#50]
i have started docker using this command
  docker run -e PUSH_FCM_APP_KEY="AIzaSyDmCafdcFrooE2n3P_ya4aQiPpD-9o" -e PUSH_APNS_ENABLED=0 -it -p 8443:8443 --rm mongooseim/mongoose-push:latest

but log says

12:20:11.931 [info]  Starting Elixir.MongoosePush.Router with Cowboy on https://0.0.0.0:8443
12:20:11.874 [error] Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':watcher(error_logger, 'Elixir.Logger.ErrorHandler', {true,false,500}) at <0.1109.0> exit with reason normal in context child_terminated
12:20:11.910 [info] Application lager started on node 'mongoose_push@127.0.0.1'
12:20:11.910 [info] Application asn1 started on node 'mongoose_push@127.0.0.1'
12:20:11.910 [info] Application crypto started on node 'mongoose_push@127.0.0.1'
12:20:11.910 [info] Application public_key started on node 'mongoose_push@127.0.0.1'
12:20:11.911 [info] Application ssl started on node 'mongoose_push@127.0.0.1'
12:20:11.911 [info] Application chatterbox started on node 'mongoose_push@127.0.0.1'
12:20:11.911 [info] Application metrics started on node 'mongoose_push@127.0.0.1'
12:20:11.911 [info] Application ssl_verify_fun started on node 'mongoose_push@127.0.0.1'
12:20:11.911 [info] Application certifi started on node 'mongoose_push@127.0.0.1'
12:20:11.911 [info] Application mimerl started on node 'mongoose_push@127.0.0.1'
12:20:11.912 [info] Application idna started on node 'mongoose_push@127.0.0.1'
12:20:11.912 [info] Application hackney started on node 'mongoose_push@127.0.0.1'
12:20:11.912 [info] Application httpoison started on node 'mongoose_push@127.0.0.1'
12:20:11.912 [info] Application pigeon started on node 'mongoose_push@127.0.0.1'
12:20:11.912 [info] Application pobox started on node 'mongoose_push@127.0.0.1'
12:20:11.913 [info] Setup running ...
12:20:11.922 [info] Directories verified. Res = ok
12:20:11.922 [info] Setup finished processing hooks (Mode=normal)...
12:20:11.922 [info] Application setup started on node 'mongoose_push@127.0.0.1'
12:20:11.929 [info] Starting reporters with []
12:20:11.929 [info] Application exometer_core started on node 'mongoose_push@127.0.0.1'
12:20:11.930 [info] Application elixometer started on node 'mongoose_push@127.0.0.1'
12:20:11.930 [info] Application exometer started on node 'mongoose_push@127.0.0.1'
12:20:11.930 [info] Application cowlib started on node 'mongoose_push@127.0.0.1'
12:20:11.930 [info] Application ranch started on node 'mongoose_push@127.0.0.1'

12:20:12.012 [info]  Starting FCM pool with API key _ya4aQiPpD-9o
12:20:12.013 [warning] lager_error_logger_h dropped 93 messages in the last second that exceeded the limit of 50 messages/sec
12:20:12.015 [info] Application mongoose_push started on node 'mongoose_push@127.0.0.1'
12:20:12.015 [info] Application iex started on node 'mongoose_push@127.0.0.1'
12:20:12.038 [info] Application sasl started on node 'mongoose_push@127.0.0.1'

**Comment by rslota** [comment]
Hi @sanghinitin ,

Since you haven't mentioned what the issue actually is, I'll assume that it's about weird API key in logs. 
For that I'll need your system info: operating system and its version, Docker edition and version and shell name with its version. Also terminal emulator name and its version could be helpful to.  

This will be probably hard to debug since I cannot reproduce this scenario on my environments (macOS 10.13 / Ubuntu 17.04 + Docker 17.09.0-ce + Zsh 5.4.2 / Bash 4.4.12), which also means that the issue is most likely environmental. 

EDIT:
Please make sure that your `mongooseim/mongoose-push:latest` is up to date (`docker pull mongooseim/mongoose-push:latest`). We need to make sure we use exactly the same image (Digest: `sha256:0736eee2f10b5e84e1ba0e1dad4c3fdd3edda1708eba81939188173d94a8d664`).

**Comment by sanghinitin** [comment]
docker details 
Docker version 17.09.0-ce, build afdb6d4
[
    {
        "Id": "sha256:cff218bcae1f9dc0f4743a88f7b89376c6529d3fb276ec3b63619c47d10c6de4",
        "RepoTags": [
            "mongooseim/mongoose-push:latest"
        ],
        "RepoDigests": [
            "mongooseim/mongoose-push@sha256:0736eee2f10b5e84e1ba0e1dad4c3fdd3edda1708eba81939188173d94a8d664"
        ],
        "Parent": "",
        "Comment": "",
        "Created": "2017-04-20T10:38:09.358622122Z",
        "Container": "514e7025d6dfd528f842954c7917c17ac3542714e3a53570ecdf405796f98a55",
        "ContainerConfig": {
            "Hostname": "bbdeb8fab105",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8443/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US.UTF-8",
                "LC_ALL=en_US.UTF-8",
                "PUSH_HTTPS_BIND_ADDR=0.0.0.0",
                "PUSH_HTTPS_PORT=8443",
                "MIX_ENV=prod",
                "REPLACE_OS_VARS=true",
                "SHELL=/bin/bash"
            ],
            "Cmd": [
                "/bin/sh",
                "-c",
                "#(nop) ",
                "ENTRYPOINT [\"/opt/app/bin/mongoose_push\"]"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:2c42750cfd12cf31669086d334982b59face1d894a0a7c5821348ce46fa47969",
            "Volumes": {
                "/opt/app/priv": {}
            },
            "WorkingDir": "/opt/app",
            "Entrypoint": [
                "/opt/app/bin/mongoose_push"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "DockerVersion": "1.12.3",
        "Author": "",
        "Config": {
            "Hostname": "bbdeb8fab105",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "ExposedPorts": {
                "8443/tcp": {}
            },
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin",
                "LANG=en_US.UTF-8",
                "LANGUAGE=en_US.UTF-8",
                "LC_ALL=en_US.UTF-8",
                "PUSH_HTTPS_BIND_ADDR=0.0.0.0",
                "PUSH_HTTPS_PORT=8443",
                "MIX_ENV=prod",
                "REPLACE_OS_VARS=true",
                "SHELL=/bin/bash"
            ],
            "Cmd": [
                "foreground"
            ],
            "ArgsEscaped": true,
            "Image": "sha256:2c42750cfd12cf31669086d334982b59face1d894a0a7c5821348ce46fa47969",
            "Volumes": {
                "/opt/app/priv": {}
            },
            "WorkingDir": "/opt/app",
            "Entrypoint": [
                "/opt/app/bin/mongoose_push"
            ],
            "OnBuild": [],
            "Labels": {}
        },
        "Architecture": "amd64",
        "Os": "linux",
        "Size": 398832463,
        "VirtualSize": 398832463,
        "GraphDriver": {
            "Data": null,
            "Name": "aufs"
        },
        "RootFS": {
            "Type": "layers",
            "Layers": [
                "sha256:745f5be9952c1a22dd4225ed6c8d7b760fe0d3583efd52f91992463b53f7aea3",
                "sha256:85782553e37a2998422ecb14fb34ac3fda94dbc90c6630d721a3bcc770939946",
                "sha256:29660d0e5bb2bae1d415f5638fa6011ab4063d1c0895e889d51ad365186d1995",
                "sha256:440e02c3dcde277c7426c07c6e240a40b1e53da4a8a0cc22a8cecd4e6f419a98",
                "sha256:56827159aa8b327a1b15c2102040ee87f3ca0bf8285aab00a1286e8af79a4beb",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:e7c3178012aac7896a7b256b66519defd50eb46086f52897d690d05de09d4318",
                "sha256:c3637b7db7bc19dbd26db3b60f99586205b5dfc95d2468107382bfeb85e1b470",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:5f70bf18a086007016e948b04aed3b82103a36bea41755b6cddfaf10ace3c6ef",
                "sha256:77e31eaa58f7d373e77aabf374994fd82dfb2bfdb6ed28ff0819723509ecdbdf",
                "sha256:59edb6a862142b93f12dbeffc5e2ad31735be612563486a955ea153e3b01f9c1",
                "sha256:44c917e9a274ecef5abcff843e149491dcefc20111b4c07f9e8fbda62afeff32",
                "sha256:aa085dfde6479106e8ab94ce957cec151fb6239679d9d53866bf82ce57a5c647",
                "sha256:23eeb6a555c4ff496fb5b0b544a5cf6e59bcb4cfd03aa17450dcbb97962d223c"
            ]
        },
        "Metadata": {
            "LastTagTime": "0001-01-01T00:00:00Z"
        }
    }
]

OS: ubuntu 16.04 LTS 
GNU bash, version 4.3.48(1)-release (x86_64-pc-linux-gnu)

API key i have changed that is not origanal key here
