### ISSUE TITLE
how to setup mongoosePush fcm & apns without docker

### ISSUE THREAD

**Issue by zaidshaikh112** [esl/MongoosePush#56]
i need a setup configuration of FCM & APNS in mongoosePush  without docker so please provide me the links for configure thanks in advance

**Comment by deadjdona** [comment]
rtfm

**Comment by rslota** [comment]
@zaidshaikh112 Please refer to the [README.md](https://github.com/esl/MongoosePush/blob/master/README.md) (_"Local build"_ section). Should you require any further help, please open a more specific issue.
