### ISSUE TITLE
a list of options for graphite

### ISSUE THREAD

**Issue by Beisenbek** [esl/MongoosePush#71]
Where I can see a list of options for graphite. I want to replace GRAPHITE_OPTIONS with a list of options for graphite. Thanks.

**Comment by rslota** [comment]
Hi @Beisenbek ,

does #72 answer you question?

**Comment by Beisenbek** [comment]
I'm looking for example configuration or explanation of `GRAPHITE_OPTIONS`: which key words should I pass for this option. 

For example, from readme we can see:
```
The example below on the other hand will enable `graphite` reporter (replace GRAPHITE_OPTIONS with a list of options for `graphite`)
 ```
So I can't find  possible list of options for `graphite`.

**Comment by rslota** [comment]
This is out of scope of this project. Please consult `exometer's` documentation: https://github.com/Feuerlabs/exometer/blob/master/doc/README.md#Configuring_graphite_reporter

**Comment by Beisenbek** [comment]
Many thanks @rslota. I assumed that there is some MongoosePush specific configuration.
