### ISSUE TITLE
Feature request: support multiple apns certificates

### ISSUE THREAD

**Issue by szjozsef** [esl/MongoosePush#77]
Feature request: support multiple apns certificates.

Using the named pool, please make the possibility to configure the apns service to be able to send PUSH notifications using multiple certificates by configuring something like this:

     {apns,
          [{dev1,
               [{endpoint,{system,string,<<"PUSH_APNS_DEV1_ENDPOINT">>,nil}},
                {cert,
                    {system,string,<<"PUSH_APNS_DEV1_CERT">>,
                        <<"priv/apns/dev1_cert.pem">>}},
                {key,
                    {system,string,<<"PUSH_APNS_DEV1_KEY">>,
                        <<"priv/apns/dev1_key.pem">>}},
                {mode,dev},
                {use_2197,{system,boolean,<<"PUSH_APNS_DEV1_USE_2197">>,false}},
                {pool_size,{system,integer,<<"PUSH_APNS_DEV1_POOL_SIZE">>,5}},
                {default_topic,
                    {system,string,<<"PUSH_APNS_DEV1_DEFAULT_TOPIC">>,nil}}]},
           {prod1,
               [{endpoint,{system,string,<<"PUSH_APNS_PROD1_ENDPOINT">>,nil}},
                {cert,
                    {system,string,<<"PUSH_APNS_PROD1_CERT">>,
                        <<"priv/apns/prod1_cert.pem">>}},
                {key,
                    {system,string,<<"PUSH_APNS_PROD1_KEY">>,
                        <<"priv/apns/prod1_key.pem">>}},
                {mode,prod},
                {use_2197,
                    {system,boolean,<<"PUSH_APNS_PROD1_USE_2197">>,false}},
                {pool_size,{system,integer,<<"PUSH_APNS_PROD1_POOL_SIZE">>,5}},
                {default_topic,
                    {system,string,<<"PUSH_APNS_PROD1_DEFAULT_TOPIC">>,
                        nil}}]},
          {dev2,
               [{endpoint,{system,string,<<"PUSH_APNS_DEV2_ENDPOINT">>,nil}},
                {cert,
                    {system,string,<<"PUSH_APNS_DEV2_CERT">>,
                        <<"priv/apns/dev2_cert.pem">>}},
                {key,
                    {system,string,<<"PUSH_APNS_DEV2_KEY">>,
                        <<"priv/apns/dev2_key.pem">>}},
                {mode,dev},
                {use_2197,{system,boolean,<<"PUSH_APNS_DEV2_USE_2197">>,false}},
                {pool_size,{system,integer,<<"PUSH_APNS_DEV2_POOL_SIZE">>,5}},
                {default_topic,
                    {system,string,<<"PUSH_APNS_DEV2_DEFAULT_TOPIC">>,nil}}]},
           {prod2,
               [{endpoint,{system,string,<<"PUSH_APNS_PROD2_ENDPOINT">>,nil}},
                {cert,
                    {system,string,<<"PUSH_APNS_PROD2_CERT">>,
                        <<"priv/apns/prod2_cert.pem">>}},
                {key,
                    {system,string,<<"PUSH_APNS_PROD2_KEY">>,
                        <<"priv/apns/prod2_key.pem">>}},
                {mode,prod},
                {use_2197,
                    {system,boolean,<<"PUSH_APNS_PROD2_USE_2197">>,false}},
                {pool_size,{system,integer,<<"PUSH_APNS_PROD2_POOL_SIZE">>,5}},
                {default_topic,
                    {system,string,<<"PUSH_APNS_PROD2_DEFAULT_TOPIC">>,
                        nil}}]}]}]},

To be able to select the correct pool, one should be able to set the pool name as "mode" in the json snet via REST API
like: `"mode":"prod1"` or `"mode":"dev2"` etc.

**Comment by rslota** [comment]
Hi @szjozsef ,

There is a new version of MongoosePush planned (no dates yet as work hasn't started yet) that will use https://github.com/esl/sparrow as its core which already allows for pool tagging and then selection of pool based on tags from request. This will somehow translate to MongoosePush API / configuration and thus, should satisfy this feature request.

**Comment by szjozsef** [comment]
Hello @rslota ,
I tried to test this with the latest docker image from a few days ago (mid November), but it seems the tags selection is not(yet) working ? It is still WIP or I'm doing something wrong ?

**Comment by rslota** [comment]
@szjozsef ,

Current version of MongoosePush (2.0.0-alpha.X) does support multiple pools that can be configured independently. This is however advanced feature that cannot be simply configured with env variables passed to docker container - in order to use this feature, you'll need to mount custom `sys.config` to the docker container. 

Can you share your steps and what is actually not working for you? This feature is still in alpha (close to beta), so there simply may be a bug that prevents this from working correctly.

**Comment by szjozsef** [comment]
Hello @rslota,
yes I copied the sys.config from the docker image and added a few lines to it, then mounted as: /opt/app/sys.config
Aslo some new environment variables was defined, like:

  PUSH_APNS_2_AUTH_TYPE=certificate
  PUSH_APNS_2_DEV_CERT=priv/apns/dev_beta_cert.pem
  PUSH_APNS_2_DEV_KEY=priv/apns/dev_beta_key.pem
  PUSH_APNS_2_PROD_CERT=priv/apns/prod_beta_cert.pem
  PUSH_APNS_2_PROD_KEY=priv/apns/prod_beta_key.pem

In the sys.config:

    {mongoose_push,
     [{fcm,
          [{default,
               [{endpoint,{system,string,<<"PUSH_FCM_ENDPOINT">>,nil}},
                {appfile,
                    {system,string,<<"PUSH_FCM_APP_FILE">>,
                        <<"priv/fcm/token.json">>}},
                {pool_size,{system,integer,<<"PUSH_FCM_POOL_SIZE">>,5}},
                {mode,prod}]}]},
      {apns,
          [{dev_Release,
               [{auth,
                    #{cert =>
                          {system,string,<<"PUSH_APNS_DEV_CERT">>,
                              <<"priv/apns/dev_cert.pem">>},
                      key =>
                          {system,string,<<"PUSH_APNS_DEV_KEY">>,
                              <<"priv/apns/dev_key.pem">>},
                      key_id => {system,string,<<"PUSH_APNS_DEV_KEY_ID">>,nil},
                      p8_file_path =>
                          {system,string,<<"PUSH_APNS_DEV_P8_TOKEN">>,
                              <<"priv/apns/token.p8">>},
                      team_id =>
                          {system,string,<<"PUSH_APNS_DEV_TEAM_ID">>,nil},
                      type => {system,atom,<<"PUSH_APNS_AUTH_TYPE">>,token}}},
                {endpoint,{system,string,<<"PUSH_APNS_DEV_ENDPOINT">>,nil}},
                {mode,dev},
                {tags,[release]},
                {use_2197,{system,boolean,<<"PUSH_APNS_DEV_USE_2197">>,false}},
                {pool_size,{system,integer,<<"PUSH_APNS_DEV_POOL_SIZE">>,5}},
                {default_topic,
                    {system,string,<<"PUSH_APNS_DEV_DEFAULT_TOPIC">>,nil}}]},
           {prod_Release,
               [{auth,
                    #{cert =>
                          {system,string,<<"PUSH_APNS_PROD_CERT">>,
                              <<"priv/apns/prod_cert.pem">>},
                      key =>
                          {system,string,<<"PUSH_APNS_PROD_KEY">>,
                              <<"priv/apns/prod_key.pem">>},
                      key_id =>
                          {system,string,<<"PUSH_APNS_PROD_KEY_ID">>,nil},
                      p8_file_path =>
                          {system,string,<<"PUSH_APNS_PROD_P8_TOKEN">>,
                              <<"priv/apns/token.p8">>},
                      team_id =>
                          {system,string,<<"PUSH_APNS_PROD_TEAM_ID">>,nil},
                      type => {system,atom,<<"PUSH_APNS_AUTH_TYPE">>,token}}},
                {endpoint,{system,string,<<"PUSH_APNS_PROD_ENDPOINT">>,nil}},
                {mode,prod},
                {tags,[release]},
                {use_2197,
                    {system,boolean,<<"PUSH_APNS_PROD_USE_2197">>,false}},
                {pool_size,{system,integer,<<"PUSH_APNS_PROD_POOL_SIZE">>,5}},
                {default_topic,
                    {system,string,<<"PUSH_APNS_PROD_DEFAULT_TOPIC">>,nil}}]},
           {dev_Beta,
               [{auth,
                    #{cert =>
                          {system,string,<<"PUSH_APNS_2_DEV_CERT">>,
                              <<"priv/apns/dev_cert.pem">>},
                      key =>
                          {system,string,<<"PUSH_APNS_2_DEV_KEY">>,
                              <<"priv/apns/dev_key.pem">>},
                      key_id => {system,string,<<"PUSH_APNS_2_DEV_KEY_ID">>,nil},
                      p8_file_path =>
                          {system,string,<<"PUSH_APNS_2_DEV_P8_TOKEN">>,
                              <<"priv/apns/token.p8">>},
                      team_id =>
                          {system,string,<<"PUSH_APNS_2_DEV_TEAM_ID">>,nil},
                      type => {system,atom,<<"PUSH_APNS_2_AUTH_TYPE">>,token}}},
                {endpoint,{system,string,<<"PUSH_APNS_2_DEV_ENDPOINT">>,nil}},
                {mode,dev},
                {tags,[beta]},
                {use_2197,{system,boolean,<<"PUSH_APNS_2_DEV_USE_2197">>,false}},
                {pool_size,{system,integer,<<"PUSH_APNS_2_DEV_POOL_SIZE">>,5}},
                {default_topic,
                    {system,string,<<"PUSH_APNS_2_DEV_DEFAULT_TOPIC">>,nil}}]},
           {prod_Beta,
               [{auth,
                    #{cert =>
                          {system,string,<<"PUSH_APNS_2_PROD_CERT">>,
                              <<"priv/apns/prod_cert.pem">>},
                      key =>
                          {system,string,<<"PUSH_APNS_2_PROD_KEY">>,
                              <<"priv/apns/prod_key.pem">>},
                      key_id =>
                          {system,string,<<"PUSH_APNS_2_PROD_KEY_ID">>,nil},
                      p8_file_path =>
                          {system,string,<<"PUSH_APNS_2_PROD_P8_TOKEN">>,
                              <<"priv/apns/token.p8">>},
                      team_id =>
                          {system,string,<<"PUSH_APNS_2_PROD_TEAM_ID">>,nil},
                      type => {system,atom,<<"PUSH_APNS_2_AUTH_TYPE">>,token}}},
                {endpoint,{system,string,<<"PUSH_APNS_2_PROD_ENDPOINT">>,nil}},
                {mode,prod},
                {tags,[beta]},
                {use_2197,
                    {system,boolean,<<"PUSH_APNS_2_PROD_USE_2197">>,false}},
                {pool_size,{system,integer,<<"PUSH_APNS_2_PROD_POOL_SIZE">>,5}},
                {default_topic,
                    {system,string,<<"PUSH_APNS_2_PROD_DEFAULT_TOPIC">>,nil}}]}]},
      {fcm_enabled,{system,boolean,<<"PUSH_FCM_ENABLED">>,true}},
      {apns_enabled,{system,boolean,<<"PUSH_APNS_ENABLED">>,true}},
      {loglevel,{system,atom,<<"PUSH_LOGLEVEL">>,info}}]},


I tried to send to both v2 and v3 RESTAPI a PUSH notification with the following values set:
`
curl -H "Content-type: application/json" -X POST -d '{"service":"apns","mode":"dev","priority":"normal","tags":["release"],"alert":{"body":"                                                                        notification text Test1","title":"notification title - just testing"}}' https://<server name>/v3/notification/<device token>
`
On the logs I can see that it selects the 2 dev pools, but choose the first one, which is the wrong one for that token:
... worker=pools_warden, action=choose_pool, result=[:dev_Beta, :dev_Release], result_len=2
Also I can confirm that in the logs the tags are present:
worker=pools_warden, action=adding_pool, pool_type={:apns, :dev}, pool_name=:dev_Release, pool_tags=[:release]
The test token is for a debug (dev) Release app, and because it get's sent with the Beta Certificate I receive:
"DeviceTokenNotForTopic", 
which by the way in v2 API translates ASIS in v3 API get's translated to: "invalid_request"


Also I had to add one more configuration to the sys.config:

                {cacertfile,
                    {system,string,<<"PUSH_HTTPS_CACERTFILE">>,
                        <<"priv/ssl/fake_cert.pem">>}},

in the section:
`
   {maru,
     [{'Elixir.MongoosePush.Router',
`
in order to define the chain certificate, otherwise just the leaf certificate is getting used for SSL, rendering it invalid, because the missing chain.

**Comment by rslota** [comment]
@szjozsef ,

Indeed it looks like a but in MongoosePush. Please take a look at #121 . This PR should be merged by tomorrow and new version of docker image will become available, that hopefully fixes the issue. 
This also includes a fix to HTTPS cert chains - now the cerfile is used both for the leaf cert and cachain.

**Comment by rslota** [comment]
Feature already in current pre-release https://github.com/esl/MongoosePush/releases/tag/2.0.0-beta.1 .
