### ISSUE TITLE
MngoosePush docker run crashes 

### ISSUE THREAD

**Issue by vimalpsojan** [esl/MongoosePush#79]
I build docker from source using 
sudo MIX_ENV=prod mix do deps.get, certs.dev, docker.build, docker.release
and when I run docker with 
command docker run -it --rm mongoose_push:release foreground
I am getting following error .
I also tried using docker image from DockerHub same error always whether I enable apns or fcm.
I have no experience in erlang or elixer , I need xmpp server with Push notification , so any help will be appreciaed  

Os Ubuntu 18.04

error 

=INFO REPORT==== 2-Nov-2018::11:24:49 ===
    msg: "Starting reporters with []\n"
    options: []
11:24:49.531 [error] Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{false,false,500}}) at <0.1201.0> exit with reason normal in context child_terminated
11:24:49.548 [info] Application lager started on node 'mongoose_push@127.0.0.1'
11:24:49.550 [info] Application elixometer started on node 'mongoose_push@127.0.0.1'
11:24:49.551 [info] Application logger_lager_backend started on node 'mongoose_push@127.0.0.1'
11:24:49.552 [info] Application mime started on node 'mongoose_push@127.0.0.1'
11:24:49.553 [info] Application crypto started on node 'mongoose_push@127.0.0.1'
11:24:49.554 [info] Application plug started on node 'mongoose_push@127.0.0.1'
11:24:49.555 [info] Application asn1 started on node 'mongoose_push@127.0.0.1'
11:24:49.556 [info] Application public_key started on node 'mongoose_push@127.0.0.1'
11:24:49.558 [info] Application ssl started on node 'mongoose_push@127.0.0.1'
11:24:49.559 [info] Application ranch started on node 'mongoose_push@127.0.0.1'
11:24:49.560 [info] Application cowlib started on node 'mongoose_push@127.0.0.1'
11:24:49.561 [info] Application cowboy started on node 'mongoose_push@127.0.0.1'
11:24:49.562 [info] Starting Elixir.MongoosePush.Router with Cowboy on https://0.0.0.0:8443
11:24:49.578 [info] Starting FCM pool with API key fake_app_key
11:24:49.580 [info] Using APNS certificate '/PL/ML/Krakow/mongoose-push-apns-dev' for 'dev' connection pool
11:24:49.580 [warning] Unable to extract APNS topic from the dev certificate due to: :no_extension
11:24:49.582 [info] Using APNS certificate '/PL/ML/Krakow/mongoose-push-apns-prod' for 'prod' connection pool
11:24:49.583 [warning] Unable to extract APNS topic from the prod certificate due to: :undef
11:24:50.041 [warning] lager_error_logger_h dropped 87 messages in the last second that exceeded the limit of 50 messages/sec
![capture](https://user-images.githubusercontent.com/44661060/47912969-5c64d800-dec0-11e8-9e27-cdc83fec10f6.PNG)

**Comment by deepakchaula** [comment]
After docker build my MongooseIM crashed....

bin/mongooseim live
Root: /home/ubuntu/update/MongooseIM/_build/prod/rel/mongooseim
Exec: /home/ubuntu/update/MongooseIM/_build/prod/rel/mongooseim/erts-10.1/bin/erlexec -boot /home/ubuntu/update/MongooseIM/_build/prod/rel/mongooseim/releases/3.2.0/mongooseim -embedded -config /home/ubuntu/update/MongooseIM/_build/prod/rel/mongooseim/etc/app.config -args_file /home/ubuntu/update/MongooseIM/_build/prod/rel/mongooseim/etc/vm.args -args_file /home/ubuntu/update/MongooseIM/_build/prod/rel/mongooseim/etc/vm.dist.args -- live
Failed to write to erl_child_setup: 32

Crash dump is being written to: erl_crash.dump...done

**Comment by deepakchaula** [comment]
@vimalpsojan did you fixed this issue?

**Comment by rslota** [comment]
@vimalpsojan ,

Can you explain what is the actual issue? The logs you've send don't really say anything alarming. 
You haven't provided command you're using to run MongoosePush other then `docker run -it --rm mongoose_push:release foreground` which obviously will start but will not work as not FCM / APNS credentials are being provided this way.

**Comment by rslota** [comment]
@deepakchaula ,

Your issue doesn't seem related to MongoosePush - you seem to start MongooseIM, so it's probably not the best place to report an issue. In addition to that, you really need to provide more details on what you're trying to build / run, what exact commands you're running, what configuration, version, etc. 
We cannot help you if we can't reproduce your issue.

**Comment by deepakchaula** [comment]
@rslota ,
docker run -v `pwd`/priv:/opt/app/priv \
  -e PUSH_FCM_APP_KEY="AAAAaatTtfA:APA91bF_hniumrn9hfRc8EVK4B6pVCoKkHonGm91z3m9tNo-b0PBZXgMQugsEAIK3CFImJAEtWKqQxwsSepuhD3cZnD1aKyJtOEFtEF3LcoakfvNhKClprlFFhiEXw8Osh_aunas1lZx" \
  -e PUSH_APNS_ENABLED=false \
  -e PUSH_LOGLEVEL=debug \
  -it --rm mongooseim/mongoose-push:latest

then after i run command:
MIX_ENV=prod mix do deps.get, certs.dev, docker.build, docker.release

After that run this:

MongoosePush/_build/prod/rel/mongoose_push/bin/mongoose_push console
Erlang/OTP 20 [erts-9.1] [source] [64-bit] [smp:1:1] [ds:1:1:10] [async-threads:10] [hipe] [kernel-poll:false]


=INFO REPORT==== 15-Jan-2019::14:47:02 ===
    msg: "Starting reporters with []\n"
    options: []
14:47:02.575 [error] Supervisor 'Elixir.Logger.Supervisor' had child 'Elixir.Logger.ErrorHandler' started with 'Elixir.Logger.Watcher':start_link({error_logger,'Elixir.Logger.ErrorHandler',{false,false,500}}) at <0.1204.0> exit with reason normal in context child_terminated
14:47:02.585 [info] Application lager started on node 'mongoose_push@127.0.0.1'
14:47:02.585 [info] Application elixometer started on node 'mongoose_push@127.0.0.1'
14:47:02.586 [info] Application logger_lager_backend started on node 'mongoose_push@127.0.0.1'
14:47:02.586 [info] Application mime started on node 'mongoose_push@127.0.0.1'
14:47:02.586 [info] Application crypto started on node 'mongoose_push@127.0.0.1'
14:47:02.586 [info] Application plug started on node 'mongoose_push@127.0.0.1'
14:47:02.587 [info] Application asn1 started on node 'mongoose_push@127.0.0.1'
14:47:02.587 [info] Application public_key started on node 'mongoose_push@127.0.0.1'
14:47:02.587 [info] Application ssl started on node 'mongoose_push@127.0.0.1'
14:47:02.587 [info] Application ranch started on node 'mongoose_push@127.0.0.1'
14:47:02.588 [info] Application cowlib started on node 'mongoose_push@127.0.0.1'
14:47:02.588 [info] Application cowboy started on node 'mongoose_push@127.0.0.1'
14:47:02.588 [info] Starting Elixir.MongoosePush.Router with Cowboy on https://127.0.0.1:8443
14:47:02.593 [info] Starting FCM pool with API key AAAAaatTtfA:APA91bF_hniumrn9hfRc8EVK4B6pVCoKkHonGm91z3m9tNo-b0PBZXgMQugsEAIK3CFImJAEtWKqQxwsSepuhD3cZnD1aKyJtOEFtEF3LcoakfvNhKClprlFFhiEXw8Osh_aunas1lZx
Interactive Elixir (1.6.1) - press Ctrl+C to exit (type h() ENTER for help)
iex(mongoose_push@127.0.0.1)1> 14:47:03.016 [warning] lager_error_logger_h dropped 87 messages in the last second that exceeded the limit of 50 messages/sec


**But after that it's not responding I am also sending push enable stanza as mention this tutorial:

https://www.erlang-solutions.com/blog/how-to-set-up-push-notifications-with-mongoosepush.html

Please help how its's work**

**Comment by rslota** [comment]
@deepakchaula ,

How do you configure MongooseIM's HTTP pool address for MongoosePush? I can see that your `docker run` for MongoosePush does not include port forwarding, which means that on macOS/Windows you'll most likely not be able to connect to this container, while on Linux you would need to reconfigure MongooseIM each time you run this container as Docker allocates IP addresses dynamically.  

EDIT:

If you would like to connect to MongoosePush via `localhost:8443` please add `-p 8443:8443` to your `docker run` command of MongoosePush.

**Comment by rslota** [comment]
But what is the output of the `curl` command? I'm assuming you've added `-p 8443:8443` as the log message you've showed would not be there if you haven't. 
Other then that, your MongoosePush should work as expected - it works for me in your configuration. 
As for MongooseIM - your MongoosePush URL is incorrect as it states `http://` instead of `https://`.

**Comment by deepakchaula** [comment]
@rslota ,
curl command output is:
null

Please explain bit more how to use -p 8443:8443 command,

and I don't have ssl certificate on my MongooseIM server.

**Comment by rslota** [comment]
Then your MongoosePush works correctly - push notification has been sent to FCM. Make sure you correct the MongooseIM configuration and it should be just fine.

**Comment by deepakchaula** [comment]
@rslota ,

Now I am getting this error in MongoosePush console:

[error] %FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :keys, kind: nil, module: Keyword}

**Comment by deepakchaula** [comment]
@rslota ,
push notifications working now in android.
Can we store device token in database like mysql ?

**Comment by deepakchaula** [comment]
@rslota ,

thanks for your kind help....

**Comment by vimalpsojan** [comment]
@anshadali 
can you please check into this one.

**Comment by rslota** [comment]
@deepakchaula ,

Device tokens are stored in Mnesia on MongooseIM side. Currently there is no support for any other database as storing tokens is "light" enough that this was never an issue. 

@vimalpsojan ,

Can you please update the issue with the description of the actual problem you're having or close it? 

> Can you explain what is the actual issue? The logs you've send don't really say anything alarming.
You haven't provided command you're using to run MongoosePush other than `docker run -it --rm mongoose_push:release foreground` which obviously will start but will not work as not FCM / APNS credentials are being provided this way. If you are providing the credentials, we need to know how in order to help you. If you don't - please refer to `README.md`.

**Comment by vimalpsojan** [comment]
@deepakchaula ,
I tried changing the os to ubuntu 16.04  , and it seems working fine. Thanks for the assistance.

**Comment by ldgabbay** [comment]
I had a very similar issue and it turned out i was setting `+P 134217727` in my `vm.args`... this exceeded the host OS kernel's limit.  i took this setting out and it finally worked.
