### ISSUE TITLE
How to edit notification/data - title and body?

### ISSUE THREAD

**Issue by shubham1164** [esl/MongoosePush#82]
I can send Notification from 1 user to another. I just want to modify the title and body before being received by 2nd user in FCM?

**Comment by michalwski** [comment]
Hi @shubham1164 you can set both title and body when sending the HTTP request to MongoosePush. See https://github.com/esl/MongoosePush#restful-api for more details.

**Comment by shubham1164** [comment]
But I have to call it manually from the server whereas by default MongoosePush work automatically, it sends the push automatically if the user is offline.

**Comment by rslota** [comment]
Hi @shubham1164 ,

Base on your comment, I'm assuming you're using MongooseIM with MongoosePush (that is an important information, as MongoosePush may be used standalone or with other software).
This also means, that this is more of a question for MongooseIM, as it is the chat server that decides what is being forwarded to MongoosePush. To be more precise: https://github.com/esl/MongooseIM/blob/427252a0c9860a713264cb0ad52ebc0dc047e6b5/src/event_pusher/mod_event_pusher_push_plugin_defaults.erl#L88 <- this function dictates how the title (`last-message-sender`) and body (`last-message-body`) will look like based on received stanza.

**Comment by shubham1164** [comment]
Many thanks :)
