### ISSUE TITLE
How to change FCM priority to high, if running via docker?

### ISSUE THREAD

**Issue by shubham1164** [esl/MongoosePush#83]
How to change FCM priority to high, if running via docker?

**Comment by rslota** [comment]
Hi @shubham1164 ,

Both FCM and APNS `priority` is an option of each of the push notifications. Therefore, you should just set the `priority` field in your HTTP request to MongoosePush to `high` (please refer to https://github.com/esl/MongoosePush#just-tell-me-what-to-send-already for more details on that). Whether you run this in Docker or not is irrelevant here.

**Comment by rslota** [comment]
@shubham1164 ,
If you're using MongoosePush wiith MongooseIM and what you're really asking is how to setup MongooseIM to set the `priority` while sending push notifications - there is no support for this yet. 
If you want to override the `priority` for every message, you may look into this part of MongooseIM code: https://github.com/esl/MongooseIM/blob/427252a0c9860a713264cb0ad52ebc0dc047e6b5/src/mod_push_service_mongoosepush.erl#L140 . This is where the MongoosePush payload is being build, so you could just add `priority => high` line. 
Ideally this should be configurable from the source device in XEP-0357 `enable` stanza, but this is not yet available.

**Comment by shubham1164** [comment]
Thanks. This makes sense to me.
